import type { Metadata } from 'next'
import { Oswald } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/ui/NavBar'
import { ClerkProvider } from '@clerk/nextjs'

const oswald = Oswald({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'note.it',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider afterSignInUrl='/' afterSignUpUrl='/'>
      <html lang="en">
        <body className={`text-[#343a40] ${oswald.className}`}>
          <NavBar/>  
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
